### ISSUE TITLE
Make it user-friendly

### ISSUE THREAD

**Issue by abhayram04** [Shree3245/ImageCopy#2]
I require an executable file of the ImageCopy service of which I very much like the use-case. 
Running this using python from command-line is too much work.

Also, please make it user-friendly by creating GUI version of the same.

**Comment by arkdev9** [comment]
I agree with @abhayram04, please consider making at least a basic gui using tkinter.

**Comment by abhayram04** [comment]
Shree Ji, please resolve our issues soon.
We believe in you 100%.

When the time comes, we will vote for you in the GitHub elections :)

Jai Shree!

**Comment by SwaritBhardwaj** [comment]
Will do! But I don't get that what buttons do you need in it's gui?

**Comment by abhayram04** [comment]
A lot of buttons my man. A lot of buttons - for every single functionality.
Btw, who are you?

**Comment by SwaritBhardwaj** [comment]
Hi, I'm Swarit currently pursuing degree in mechatronics. I'm sorry I was busy from a few days so I wasn't able to reply earlier, and I have a busy schedule for a few more days after that I'll get right on this. Till then I request you to give a detailed description of what else buttons do we need apart from targeting the location of the image and copying the image, and what kind of interface or layout you have in mind. Also there is this other error 
```
Traceback (most recent call last):
  File "C:/Users/bsbha/Desktop/git test1.py", line 16, in <module>
    image.convert("RGB").save(output, "BMP")
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 2158, in save
    save_handler(self, fp, filename)
  File "C:\Python37\lib\site-packages\PIL\BmpImagePlugin.py", line 331, in _save
    + o32(offset)  # image data offset
TypeError: string argument expected, got 'bytes'
```
The other day I was trying to run the code, but an error comes up saying  no module found named as PIL (I have pillow installed), it shows no error when I write pil but it doesn't works for the image.

**Comment by arkdev9** [comment]
`image.convert()` expects a string argument, probably base64 encoded image data, but you're passing it `output` which is raw bytes. Can you give us more information on that error.
